add_lunch_combo ose_flo-userdebug
add_lunch_combo ose_grouper-userdebug
add_lunch_combo ose_ls980-userdebug
add_lunch_combo ose_vs980-userdebug
add_lunch_combo ose_vs985-userdebug
add_lunch_combo ose_d800-userdebug
add_lunch_combo ose_d801-userdebug
add_lunch_combo ose_d802-userdebug
add_lunch_combo ose_d803-userdebug
add_lunch_combo ose_d850-userdebug

